/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.devweb.plocadora.web.api;

import com.devweb.plocadora.web.model.ClasseApiModel;
import com.devweb.plocadora.web.model.ClasseCriadaApiModel;
import com.devweb.plocadora.web.model.ErroRequisicaoApiModel;
import com.devweb.plocadora.web.model.NovaClasseApiModel;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Tag(name = "classe", description = "the classe API")
public interface ClasseApi {

    /**
     * POST /classe : Create New User
     * Create a new user.
     *
     * @param novaClasseApiModel Post the necessary fields for the API to create a new user. (optional)
     * @return User Created (status code 201)
     *         or Missing Required Information (status code 400)
     *         or Email Already Taken (status code 500)
     */
    @Operation(
        operationId = "cadastroClasse",
        summary = "Create New User",
        description = "Create a new user.",
        responses = {
            @ApiResponse(responseCode = "201", description = "User Created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ClasseCriadaApiModel.class))
            }),
            @ApiResponse(responseCode = "400", description = "Missing Required Information", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErroRequisicaoApiModel.class))
            }),
            @ApiResponse(responseCode = "500", description = "Email Already Taken", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErroRequisicaoApiModel.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/classe",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<ClasseCriadaApiModel> cadastroClasse(
        @Parameter(name = "NovaClasseApiModel", description = "Post the necessary fields for the API to create a new user.") @Valid @RequestBody(required = false) NovaClasseApiModel novaClasseApiModel
    );


    /**
     * DELETE /classe/{classeId} : 
     *
     * @param classeId  (required)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "deleteClasse",
        summary = "",
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ClasseApiModel.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErroRequisicaoApiModel.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErroRequisicaoApiModel.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/classe/{classeId}",
        produces = { "application/json" }
    )
    
    ResponseEntity<ClasseApiModel> deleteClasse(
        @Parameter(name = "classeId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("classeId") String classeId
    );


    /**
     * GET /classe/{classeId} : Your GET endpoint
     *
     * @param classeId  (required)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "getClasse",
        summary = "Your GET endpoint",
        tags = {  },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ClasseApiModel.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErroRequisicaoApiModel.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErroRequisicaoApiModel.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/classe/{classeId}",
        produces = { "application/json" }
    )
    
    ResponseEntity<ClasseApiModel> getClasse(
        @Parameter(name = "classeId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("classeId") String classeId
    );


    /**
     * GET /classe : 
     *
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "getClasses",
        summary = "",
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = ClasseApiModel.class)))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErroRequisicaoApiModel.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErroRequisicaoApiModel.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/classe",
        produces = { "application/json" }
    )
    
    ResponseEntity<List<ClasseApiModel>> getClasses(
        
    );


    /**
     * PUT /classe/{classeId} : 
     *
     * @param classeId  (required)
     * @param classeApiModel  (optional)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "putClasse",
        summary = "",
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ClasseApiModel.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErroRequisicaoApiModel.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErroRequisicaoApiModel.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/classe/{classeId}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<ClasseApiModel> putClasse(
        @Parameter(name = "classeId", description = "", required = true, in = ParameterIn.PATH) @PathVariable("classeId") String classeId,
        @Parameter(name = "ClasseApiModel", description = "") @Valid @RequestBody(required = false) ClasseApiModel classeApiModel
    );

}
