/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.2.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.devweb.plocadora.web.api;

import com.devweb.plocadora.web.model.AtualizarDiretorApiModel;
import com.devweb.plocadora.web.model.DiretorApiModel;
import com.devweb.plocadora.web.model.DiretorCriadoApiModel;
import com.devweb.plocadora.web.model.ErroRequisicaoApiModel;
import com.devweb.plocadora.web.model.NovoDiretorApiModel;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
@Validated
@Tag(name = "diretor", description = "the diretor API")
public interface DiretorApi {

    /**
     * DELETE /diretor/{diretor_id} : 
     *
     * @param diretorId  (required)
     * @return No Content (status code 204)
     *         or Bad Request (status code 400)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "deleteDiretor",
        summary = "",
        responses = {
            @ApiResponse(responseCode = "204", description = "No Content"),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErroRequisicaoApiModel.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErroRequisicaoApiModel.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/diretor/{diretor_id}",
        produces = { "application/json" }
    )
    
    ResponseEntity<Void> deleteDiretor(
        @Parameter(name = "diretor_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("diretor_id") String diretorId
    );


    /**
     * GET /diretor/{diretor_id} : Your GET endpoint
     *
     * @param diretorId  (required)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "getDiretor",
        summary = "Your GET endpoint",
        tags = {  },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DiretorApiModel.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErroRequisicaoApiModel.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErroRequisicaoApiModel.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/diretor/{diretor_id}",
        produces = { "application/json" }
    )
    
    ResponseEntity<DiretorApiModel> getDiretor(
        @Parameter(name = "diretor_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("diretor_id") String diretorId
    );


    /**
     * GET /diretor : Your GET endpoint
     *
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "getDiretores",
        summary = "Your GET endpoint",
        tags = {  },
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = DiretorApiModel.class)))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErroRequisicaoApiModel.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErroRequisicaoApiModel.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/diretor",
        produces = { "application/json" }
    )
    
    ResponseEntity<List<DiretorApiModel>> getDiretores(
        
    );


    /**
     * POST /diretor : 
     *
     * @param novoDiretorApiModel  (optional)
     * @return Created (status code 201)
     *         or Bad Request (status code 400)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "postDiretor",
        summary = "",
        responses = {
            @ApiResponse(responseCode = "201", description = "Created", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DiretorCriadoApiModel.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErroRequisicaoApiModel.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErroRequisicaoApiModel.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/diretor",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<DiretorCriadoApiModel> postDiretor(
        @Parameter(name = "NovoDiretorApiModel", description = "") @Valid @RequestBody(required = false) NovoDiretorApiModel novoDiretorApiModel
    );


    /**
     * PUT /diretor/{diretor_id} : 
     *
     * @param diretorId  (required)
     * @param atualizarDiretorApiModel  (optional)
     * @return OK (status code 200)
     *         or Bad Request (status code 400)
     *         or Internal Server Error (status code 500)
     */
    @Operation(
        operationId = "putDiretor",
        summary = "",
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = DiretorApiModel.class))
            }),
            @ApiResponse(responseCode = "400", description = "Bad Request", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErroRequisicaoApiModel.class))
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ErroRequisicaoApiModel.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/diretor/{diretor_id}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    ResponseEntity<DiretorApiModel> putDiretor(
        @Parameter(name = "diretor_id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("diretor_id") String diretorId,
        @Parameter(name = "AtualizarDiretorApiModel", description = "") @Valid @RequestBody(required = false) AtualizarDiretorApiModel atualizarDiretorApiModel
    );

}
